//
// RecipeList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RecipeList: Codable {

    public var title: String?
    public var results: [Recipe]?

    public init(title: String? = nil, results: [Recipe]? = nil) {
        self.title = title
        self.results = results
    }


}
