//
// RecipeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class RecipeAPI {
    /**
     Get Recipe

     - parameter i: (query) Ingredient 
     - parameter q: (query) Query (optional)
     - parameter p: (query) Paging (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getRecipe(i: String, q: String? = nil, p: Int? = nil, completion: @escaping ((_ data: RecipeList?,_ error: Error?) -> Void)) {
        getRecipeWithRequestBuilder(i: i, q: q, p: p).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get Recipe
     - GET /api/
     - 

     - examples: [{contentType=application/json, example={
  "title" : "title",
  "results" : [ {
    "thumbnail" : "thumbnail",
    "ingredients" : "ingredients",
    "href" : "href",
    "title" : "title"
  }, {
    "thumbnail" : "thumbnail",
    "ingredients" : "ingredients",
    "href" : "href",
    "title" : "title"
  } ]
}}]
     - parameter i: (query) Ingredient 
     - parameter q: (query) Query (optional)
     - parameter p: (query) Paging (optional)

     - returns: RequestBuilder<RecipeList> 
     */
    open class func getRecipeWithRequestBuilder(i: String, q: String? = nil, p: Int? = nil) -> RequestBuilder<RecipeList> {
        let path = "/api/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "i": i, 
                        "q": q, 
                        "p": p?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<RecipeList>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
